config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors, path: 'doctors', controllers: { sessions: 'doctors/sessions' }
  devise_for :patients, path: 'patients', controllers: { sessions: 'patients/sessions' }

  root to: 'welcome#index'

  get 'welcome/index'
  get 'welcome/doctors', to: 'welcome#doctors', as: 'welcome_doctors'
  get 'welcome/doctor/:id', to: 'welcome#doctor', as: 'welcome_doctor'

  resources :patients, except: %i[destroy index]
  get 'dashboard/patients', to: 'patients#dashboard', as: 'dashboard_patients'

  resources :doctors, except: %i[index show destroy]
  get 'dashboard/doctors', to: 'doctors#dashboard', as: 'dashboard_doctors'

  resources :visits, except: :show

  resources :offices, except: :show
end

app/models/office.rb
class Office < ApplicationRecord
  belongs_to :doctor

  def name
    "#{city}, #{street}"
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  include AccessibleDoctors

  before_action :authenticate_doctor!
  before_action :set_office, only: %i[edit update destroy]

  def index
    @offices = Office.where(doctor_id: current_doctor.id)
  end

  def new
    @office = Office.new(doctor_id: current_doctor.id)
  end

  def create
    @office = Office.new(office_params)
    @office.doctor_id = current_doctor.id

    if @office.save
      flash[:notice] = 'Office created successfully.'
      redirect_to(offices_path)
    else
      render('new')
    end
  end

  def edit
  end

  def update
    if @office.update_attributes(office_params)
      flash[:notice] = 'Office updated successfully'
      redirect_to(offices_path)
    else
      render('edit')
    end
  end

  def destroy
    @office.destroy
  end

  private

  def office_params
    params.require(:office).permit(:city, :postal_code, :street, :nr, :info)
  end

  def set_office
    @office = Office.find(params[:id])
  end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<table summary="Office form fields">
  <tr>
    <th>City</th>
    <td><%= f.text_field(:city) %></td>
  </tr>
  <tr>
    <th>Postal code</th>
    <td><%= f.text_field(:postal_code) %></td>
  </tr>
  <tr>
    <th>Street</th>
    <td><%= f.text_field(:street) %></td>
  </tr>
  <tr>
    <th>Nr</th>
    <td><%= f.text_field(:nr) %></td>
  </tr>
  <tr>
    <th>Info</th>
    <td><%= f.text_area(:info) %></td>
  </tr>
</table>

app/views/offices/create.html.erb
<h1>Offices#create</h1>
<p>Find me in app/views/offices/create.html.erb</p>

app/views/offices/destroy.html.erb
<h1>Offices#destroy</h1>
<p>Find me in app/views/offices/destroy.html.erb</p>

app/views/offices/edit.html.erb
<% title 'Doctor' %>

<%= link_to('<< Back to List', offices_path) %>

<%= form_for(@office, url: office_path, method: 'patch') do |f| %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <div>
      <%= f.submit('Update Office') %>
    </div>

<% end %>

app/views/offices/index.html.erb
<% title 'Doctor' %>

<%= link_to('New', new_office_path, class: 'btn btn-primary') %>
<br/>
<table class="table" summary="My offices">
  <tr>
    <th>City</th>
    <th>Postal code</th>
    <th>Street</th>
    <th>Nr</th>
    <th>Info</th>
    <th>Actions</th>
  </tr>
  <% @offices.each do |office| %>
      <tr>
        <td><%= office.city %> </td>
        <td><%= office.postal_code %></td>
        <td><%= office.street %></td>
        <td><%= office.nr %></td>
        <td><%= office.info %></td>
        <td>
          <%= link_to('Visits', visits_path(office_id: office.id), class: 'btn btn-primary') %>
          <%= link_to('Edit', edit_office_path(office), class: 'btn btn-primary') %>
          <%= link_to('Delete', office_path(office), method: 'delete',
                      class: 'btn btn-primary') %>
        </td>
      </tr>
  <% end %>
</table>

app/views/offices/new.html.erb
<% title 'Doctor' %>

<%= link_to('<< Back to List', offices_path) %>

<%= form_for(@office, url: offices_path, method: 'post') do |f| %>

    <%= render(partial: 'form', locals: {f: f}) %>

    <div>
      <%= f.submit('Create Office') %>
    </div>

<% end %>

app/views/offices/update.html.erb
<h1>Offices#update</h1>
<p>Find me in app/views/offices/update.html.erb</p>