config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors, path: 'doctors', controllers: { sessions: 'doctors/sessions' }
  devise_for :patients, path: 'patients', controllers: { sessions: 'patients/sessions' }

  root to: 'welcome#index'

  get 'welcome/index'
  get 'welcome/doctors', to: 'welcome#doctors', as: 'welcome_doctors'
  get 'welcome/doctor/:id', to: 'welcome#doctor', as: 'welcome_doctor'

  resources :patients, except: %i[destroy index]
  get 'dashboard/patients', to: 'patients#dashboard', as: 'dashboard_patients'

  resources :doctors, except: %i[index show destroy]
  get 'dashboard/doctors', to: 'doctors#dashboard', as: 'dashboard_doctors'

  resources :visits, except: :show

  resources :offices, except: :show
end

app/models/patient.rb
class Patient < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :visits

  def name
    "#{first_name} #{last_name}"
  end

  validates :email, uniqueness: true



end

app/controllers/patients/confirmations_controller.rb
class Patients::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/patients/omniauth_callbacks_controller.rb
class Patients::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/patients/passwords_controller.rb
class Patients::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/patients/registrations_controller.rb
class Patients::RegistrationsController < Devise::RegistrationsController
  include AccessiblePatients
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    redirect_to(dashboard_patients_path)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/patients/sessions_controller.rb
class Patients::SessionsController < Devise::SessionsController
  include AccessiblePatients

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message! :notice, :signed_out if signed_out
    yield if block_given?

    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) { redirect_to(root_path) }
    end
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/patients/unlocks_controller.rb
class Patients::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  include AccessiblePatients

  before_action :authenticate_patient!
  before_action :set_patient, only: %i[update edit]

  def show
    @patient = current_patient
  end

  def edit
    unless params[:id].to_i == current_patient.id
      flash[:alert] = 'Prohibited action'
      redirect_to(root_path)
    end
  end

  def update
    if @patient.update_attributes(patient_params)
      flash[:notice] = 'Updated successfully'
      redirect_to(dashboard_patients_path)
    else
      render('edit')
    end
  end

  def dashboard
    redirect_to(new_patient_session_path) unless current_patient
    @patient = current_patient
  end

  private

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :email, :phone)
  end

  def set_patient
    @patient = Patient.find(params[:id])
  end

end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/create.html.erb
<h1>Patients#create</h1>
<p>Find me in app/views/patients/create.html.erb</p>

app/views/patients/dashboard.html.erb
<% title 'Patient' %>

<p>Patient <%= @patient.email %></p>


<%= link_to('Edit personal info', edit_patient_path(id: @patient.id)) %>

<br/>

<%= link_to('Edit credentials', edit_patient_registration_path) %>

<br/>

<%= link_to('My visits', visits_path) %>

<br/>

<%= link_to('Logout', destroy_patient_session_path, method: 'delete') %>

app/views/patients/edit.html.erb
<% title 'Patient' %>

<%= link_to('<< Cancel', dashboard_patients_path) %>

<div>
  <h2>Edit data</h2>

  <%= form_for(@patient, url: patient_path(@patient), method: 'patch') do |f| %>

      <table>
        <tr>
          <th>First name</th>
          <td><%= f.text_field(:first_name) %></td>
        </tr>
        <tr>
          <th>Last name</th>
          <td><%= f.text_field(:last_name) %></td>
        </tr>
        <tr>
          <th>Phone number</th>
          <td><%= f.text_field(:phone) %></td>
        </tr>
      </table>

      <div class="form-buttons">
        <%= f.submit('Save') %>
      </div>

  <% end %>
</div>

app/views/patients/show.html.erb
<h1>Patients#show</h1>
<p>Find me in app/views/patients/show.html.erb</p>

app/views/patients/visits.html.erb
<% title 'Patient' %>

<table class="table" summary="My visits">
  <tr>
    <th>Name</th>
    <th>Contact</th>
    <th>Office</th>
    <th>Date and time</th>
  </tr>
  <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.doctor.name %></td>
        <td><%= visit.doctor.phone %>
          <%= visit.doctor.email %></td>
        <td><%= visit.office.postal_code %> <%= visit.office.city %> <br/>
          <%= visit.office.street %> <%= visit.office.nr %></td>
        <td class="center"> <%= visit.start_time %></td>
      </tr>
  <% end %>
</table>