config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors, path: 'doctors', controllers: { sessions: 'doctors/sessions' }
  devise_for :patients, path: 'patients', controllers: { sessions: 'patients/sessions' }

  root to: 'welcome#index'

  get 'welcome/index'
  get 'welcome/doctors', to: 'welcome#doctors', as: 'welcome_doctors'
  get 'welcome/doctor/:id', to: 'welcome#doctor', as: 'welcome_doctor'

  resources :patients, except: %i[destroy index]
  get 'dashboard/patients', to: 'patients#dashboard', as: 'dashboard_patients'

  resources :doctors, except: %i[index show destroy]
  get 'dashboard/doctors', to: 'doctors#dashboard', as: 'dashboard_doctors'

  resources :visits, except: :show

  resources :offices, except: :show
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :visits
  has_many :offices
  has_many :timetables

  scope :sorted, -> { order(created_at: :desc) }

  def self.search search_specialization, search_city
    return sorted if search_specialization.blank? && search_city.blank?

    where(['upper(specialization) LIKE upper(?)', "%#{search_specialization}%"])
      .joins(:offices).where(['upper(city) LIKE upper(?)', "%#{search_city}%"])
  end

  def name
    "#{title} #{first_name} #{last_name}"
  end
end

app/controllers/doctors/confirmations_controller.rb
class Doctors::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/doctors/omniauth_callbacks_controller.rb
class Doctors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/doctors/passwords_controller.rb
class Doctors::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/doctors/registrations_controller.rb
class Doctors::RegistrationsController < Devise::RegistrationsController
  include AccessibleDoctors
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    redirect_to(dashboard_doctors_path)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/doctors/sessions_controller.rb
class Doctors::SessionsController < Devise::SessionsController
  include AccessibleDoctors
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message! :notice, :signed_out if signed_out
    yield if block_given?

    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) { redirect_to(root_path) }
    end
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/doctors/unlocks_controller.rb
class Doctors::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  include AccessibleDoctors

  before_action :authenticate_doctor!
  before_action :set_doctor, only: %i[edit update]

  def edit
    unless params[:id].to_i == current_doctor.id
      flash[:alert] = 'Prohibited action'
      redirect_to(root_path) && return
    end
  end

  def update
    if @doctor.update_attributes(doctor_params)
      flash[:notice] = 'Updated successfully'
      redirect_to(dashboard_doctors_path)
    else
      render('edit')
    end
  end

  def dashboard
    redirect_to(new_doctor_session_path) unless current_doctor
    @doctor = current_doctor
  end

  private

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name, :title, :phone, :specialization,
                                   :description)
  end

  def set_doctor
    @office = Office.find(params[:id])
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/create.html.erb
<h1>Doctors#create</h1>
<p>Find me in app/views/doctors/create.html.erb</p>

app/views/doctors/dashboard.html.erb
<p>Doctor <%= @doctor.email %></p>

<%= link_to('Edit info', edit_doctor_path(id: @doctor.id)) %>

<br/>

<%= link_to('Edit credentials', edit_doctor_registration_path) %>

<br/>

<%= link_to('My visits', visits_path) %>

<br/>

<%= link_to('My offices', offices_path) %>

<br/>

<%= link_to('Logout', destroy_doctor_session_path, method: 'delete') %>

app/views/doctors/edit.html.erb
<%= link_to('<< Cancel', dashboard_doctors_path) %>

<div>
  <h2>Edit info</h2>

  <%= form_for(@doctor, url: doctor_path(@doctor), method: 'patch') do |f| %>

      <table>
        <tr>
          <th>First name</th>
          <td><%= f.text_field(:first_name) %></td>
        </tr>
        <tr>
          <th>Last name</th>
          <td><%= f.text_field(:last_name) %></td>
        </tr>
        <tr>
          <th>Phone number</th>
          <td><%= f.text_field(:phone) %></td>
        </tr>
        <tr>
          <th>Specialization</th>
          <td><%= f.text_field(:specialization) %></td>
        </tr>
        <tr>
          <th>Description</th>
          <td><%= f.text_area(:description) %></td>
        </tr>
      </table>

      <div class="form-buttons">
        <%= f.submit('Save') %>
      </div>

  <% end %>
</div>

app/views/doctors/index.html.erb
<% if @doctors %>
  <table class="table table-striped table-hover" summary="Page list">
    <tr class="header">
      <th>Imie</th>
      <th>Nazwisko</th>
      <th></th>
      <!--<th>Visible</th>-->
      <!--<th>Permlink</th>-->
      <!--<th>Sections</th>-->
      <!--<th>Actions</th>-->
    </tr>

    <% @doctors.each do |doctor| %>

        <tr>
          <td><%= doctor.first_name %></td>
          <td><%= doctor.last_name %></td>
          <td><%= link_to('Pokaz profil', doctor_path(id: doctor.id ), class: 'btn btn-primary')
          %></td>
          <!--<td></td>-->
          <!--<td></td>-->
        </tr>
    <% end %>
  </table>
<% else %>
 <p>Brak Danych</p>
<% end %>

app/views/doctors/new.html.erb
<h1>Doctors#new</h1>
<p>Find me in app/views/doctors/new.html.erb</p>

app/views/doctors/show.html.erb
<table>
  <tr>
    <td><%= @doctor.name%></td>
  </tr>
  <tr>
    <td><%= @doctor.email %></td>
  </tr>
  <tr>
    <td><%= @doctor.phone %></td>
  </tr>
  <tr>
    <td><%= @doctor.description %></td>
  </tr>
</table>

app/views/doctors/update.html.erb
<h1>Doctors#update</h1>
<p>Find me in app/views/doctors/update.html.erb</p>