config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors, path: 'doctors', controllers: { sessions: 'doctors/sessions' }
  devise_for :patients, path: 'patients', controllers: { sessions: 'patients/sessions' }

  root to: 'welcome#index'

  get 'welcome/index'
  get 'welcome/doctors', to: 'welcome#doctors', as: 'welcome_doctors'
  get 'welcome/doctor/:id', to: 'welcome#doctor', as: 'welcome_doctor'

  resources :patients, except: %i[destroy index]
  get 'dashboard/patients', to: 'patients#dashboard', as: 'dashboard_patients'

  resources :doctors, except: %i[index show destroy]
  get 'dashboard/doctors', to: 'doctors#dashboard', as: 'dashboard_doctors'

  resources :visits, except: :show

  resources :offices, except: :show
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || 'Find Doctor' %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header" >
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= link_to('Find Doctor', root_path, class: 'navbar-brand logo') %>
          </div>
          <ul class="nav nav-pills navbar-right">
            <li role="presentation" class="<%= 'active' if @page_title == 'Patient' %>">
              <%= link_to('Patient', dashboard_patients_path, class: 'navbar-brand')
              %></a></li>
            <li role="presentation" class="<%= 'active' if @page_title == 'Doctor' %>">
              <%= link_to('Doctor', dashboard_doctors_path, class: 'navbar-brand') %></li>
          </ul>
          <% if signed_in? %>
              <p class="navbar-text navbar-right" style="margin-right: 40px;">Logged as
                <% if patient_signed_in? then %>
                    patient <%= current_patient.email %>
                <% else %>
                    doctor <%= current_doctor.email %>
                <% end %>
              </p>
          <% end %>
        </div>
      </nav>
    </div>
    <div id="container">

      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>

      <div id="content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>